# Generated by Django 3.0.8 on 2020-07-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationNameForSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=60)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrote_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('tag_string', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RoomForSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_people_count', models.SmallIntegerField()),
                ('max_people_count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostOfRequestSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('tag_kind', models.TextField(null=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfRecruitSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('tag_kind', models.TextField(null=True)),
                ('min_people_count', models.SmallIntegerField(default=0)),
                ('max_people_count', models.SmallIntegerField(default=0)),
                ('times_of_class', models.SmallIntegerField(default=0)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfFreeSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanOfSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=20)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='seminar.RoomForSeminar')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='seminar.PlannedSeminar')),
            ],
        ),
        migrations.AddField(
            model_name='plannedseminar',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='seminar.PostOfRecruitSeminar'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.CharField(max_length=200)),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
                ('ref_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='seminar.Link')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='seminar.Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ref_link', 'user')},
            },
        ),
    ]
