# Generated by Django 3.0.8 on 2020-07-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_auto_20200719_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plantitle', models.CharField(max_length=60)),
                ('PlanStart', models.CharField(max_length=60)),
                ('PlanEnd', models.CharField(max_length=60)),
            ],
        ),
    ]
