# Generated by Django 3.0.8 on 2020-07-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='plan_id',
            field=models.UUIDField(null=True),
        ),
    ]
