# Generated by Django 3.0.8 on 2020-07-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_calendar_plan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['-PlanStart']},
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='Plantitle',
            new_name='title',
        ),
    ]
