# Generated by Django 3.0.7 on 2020-06-24 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('seminar', '0001_initial'), ('seminar', '0002_recommend_user'), ('seminar', '0003_auto_20200624_0839'), ('seminar', '0004_auto_20200624_1039'), ('seminar', '0005_auto_20200624_1043'), ('seminar', '0006_auto_20200624_1044'), ('seminar', '0007_auto_20200624_1044'), ('seminar', '0008_auto_20200624_1044'), ('seminar', '0009_auto_20200624_1050'), ('seminar', '0010_auto_20200624_1055'), ('seminar', '0011_auto_20200624_1057'), ('seminar', '0012_auto_20200624_1101'), ('seminar', '0013_auto_20200624_1124')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=60)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrote_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('profile_url', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.CharField(max_length=200)),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('ref_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='seminar.Link')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='PostOfFreeSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfRecruitSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('tag_kind', models.TextField(null=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfRequestSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('tag_kind', models.TextField(null=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='seminar.Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ref_link', 'user')},
            },
        ),
    ]
