# Generated by Django 3.0.7 on 2020-06-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('seminar', '0002_roomforseminar'), ('seminar', '0003_auto_20200624_1151'), ('seminar', '0004_plannedseminar'), ('seminar', '0005_auto_20200624_1636'), ('seminar', '0006_plannedseminar_tagstring'), ('seminar', '0007_auto_20200624_1711')]

    dependencies = [
        ('seminar', '0001_initial_squashed_0013_auto_20200624_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomForSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_people_count', models.SmallIntegerField(default=0)),
                ('min_people_count', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DurationNameForSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='seminar.PostOfRecruitSeminar')),
                ('tag_string', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
