# Generated by Django 3.0.7 on 2020-06-23 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_free_seminar',
            new_name='PostFreeSeminar',
        ),
    ]
