# Generated by Django 3.0.7 on 2020-06-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_remove_userdata_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes',
            new_name='vote_count',
        ),
    ]
