# Generated by Django 3.0.7 on 2020-06-23 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0002_recommend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommends', to=settings.AUTH_USER_MODEL),
        ),
    ]
