# Generated by Django 3.0.7 on 2020-06-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_auto_20200624_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='recommend',
            old_name='comment_date',
            new_name='recommend_date',
        ),
    ]
