# Generated by Django 3.0.7 on 2020-06-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_auto_20200624_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='link',
            new_name='ref_link',
        ),
    ]
