# Generated by Django 3.0.7 on 2020-06-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_auto_20200624_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='link',
            new_name='ref_link',
        ),
    ]
