# Generated by Django 3.0.7 on 2020-06-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_auto_20200624_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
    ]
