# Generated by Django 3.0.7 on 2020-06-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_auto_20200624_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='title',
            new_name='namespace',
        ),
    ]
