# Generated by Django 3.0.7 on 2020-06-24 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0009_auto_20200624_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link', unique=True),
        ),
        migrations.AlterField(
            model_name='postoffreeseminar',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link', unique=True),
        ),
        migrations.AlterField(
            model_name='postofrecruitseminar',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link', unique=True),
        ),
        migrations.AlterField(
            model_name='postofrequestseminar',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link', unique=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='recommend',
            unique_together={('ref_link', 'user')},
        ),
    ]
