# Generated by Django 3.0.7 on 2020-06-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0010_auto_20200624_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
        migrations.AlterField(
            model_name='postoffreeseminar',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
        migrations.AlterField(
            model_name='postofrecruitseminar',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
        migrations.AlterField(
            model_name='postofrequestseminar',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Link'),
        ),
    ]
