# Generated by Django 3.0.7 on 2020-06-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0012_auto_20200624_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='recommend_date',
        ),
    ]
